# Uncomment the next line to define a global platform for your project
platform :ios, '11.1'
  use_frameworks!

target 'ActionStats' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ActionStats
  pod 'Alamofire', '~> 4.5'

  target 'ActionStatsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ActionStatsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
