# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.5.0-node-browsers

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "server/Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            cd server && bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - server/vendor/bundle
          key: v1-dependencies-{{ checksum "server/Gemfile.lock" }}

      - run:
          name: rubocop
          command: |
            cd server && bundle exec rubocop --config .rubocop.yml
